language: python
python:
 - "2.7"
install:
  - pip install --no-deps -r requirements/dev.txt --find-links https://pyrepo.addons.mozilla.org/
before_script:
  - flake8 .
script: ./manage.py test --noinput -s
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
